In [1]:
distance = input("Input distance of trip in miles: ")

Input distance of trip in miles: 450


In [4]:
distance

'450'

In [7]:
type(distance)

str

In [3]:
eval(distance) #converte em número inteiro

450

In [10]:
distance

'450'

In [11]:
distance = eval(distance)

In [12]:
distance

450

In [13]:
distance = float(distance)

In [14]:
distance

450.0

In [27]:
# Calculates time, gallons of gas used, and cost of gasoline for
# a trip

distance = input("Input distance of trip in miles: ")
distance = float(distance)

mpg = 30. # car mileage
speed = 60. # average speed
costPerGallon = 4.10 # price of gas

time = distance/speed
gallons = distance/mpg
cost = gallons*costPerGallon

print("\nDuration of trip = {0:0.1f} hours".format(time))                     
print("Gasoline used = {0:0.1f} gallons (@ {1:0.0f} mpg)".format(gallons, mpg))        #valor antes ":"  --> posição em format
print("Cost of gasoline = ${0:0.2f} (@ ${1:0.2f}/gallon)".format(cost, costPerGallon))


Input distance of trip in miles: 450

Duration of trip = 7.5 hours
Gasoline used = 15.0 gallons (@ 30 mpg)
Cost of gasoline = $61.50 (@ $4.10/gallon)


In [28]:
string1 = "How"
string2 = "are you my friend?"
int1 = 34
int2 = 942885
float1 = -3.0
float2 = 3.141592653589793e-14

print(' ***')
print(string1)
print(string1 + ' ' + string2)
print(' 1. {} {}'.format(string1, string2))
print(' 2. {0:s} {1:s}'.format(string1, string2))
print(' 3. {0:s} {0:s} {1:s} - {0:s} {1:s}'.format(string1, string2))
print(' 4. {0:10s}{1:5s}'.format(string1, string2))
print(' ***')
print(int1, int2)
print(' 6. {0:d} {1:d}'.format(int1, int2))
print(' 7. {0:8d} {1:10d}'.format(int1, int2))
print(' ***')
print(' 8. {0:0.3f}'.format(float1))
print(' 9. {0:6.3f}'.format(float1))
print('10. {0:8.3f}'.format(float1))
print(2*'11. {0:8.3f}'.format(float1))
print(' ***')
print('12. {0:0.3e}'.format(float2))
print('13. {0:10.3e}'.format(float2))
print('14. {0:10.3f}'.format(float2))
print(' ***')
print('15. 12345678901234567890')
print('16. {0:s}--{1:8d},{2:10.3e}'.format(string2, int1, float2))

#Não entendi muito bem a questão do espaçamento nos códigos 9 a 16... ver depois.

 ***
How
How are you my friend?
 1. How are you my friend?
 2. How are you my friend?
 3. How How are you my friend? - How are you my friend?
 4. How       are you my friend?
 ***
34 942885
 6. 34 942885
 7.       34     942885
 ***
 8. -3.000
 9. -3.000
10.   -3.000
11.   -3.00011.   -3.000
 ***
12. 3.142e-14
13.  3.142e-14
14.      0.000
 ***
15. 12345678901234567890
16. are you my friend?--      34, 3.142e-14


In [39]:
import numpy as np
a = np.linspace(3, 19, 7)
print(a)

np.set_printoptions(precision=2)
b = np.linspace(3, 19, 7)
print("\n", b)

np.set_printoptions(formatter={'float': lambda x: format(x, '6.2e')})
c = np.linspace(3, 19, 7)
print("\n", c)

np.set_printoptions(formatter={'float': lambda x: format(x, '6.3f')})
d = np.linspace(3, 19, 7)
print("\n", d)

np.set_printoptions(precision=8)
e = np.linspace(3, 19, 7)
print("\n", e)

[  3.     5.67   8.33  11.    13.67  16.33  19.  ]

 [  3.     5.67   8.33  11.    13.67  16.33  19.  ]

 [3.00e+00 5.67e+00 8.33e+00 1.10e+01 1.37e+01 1.63e+01 1.90e+01]

 [ 3.000  5.667  8.333 11.000 13.667 16.333 19.000]

 [  3.           5.66666667   8.33333333  11.          13.66666667
  16.33333333  19.        ]


In [37]:

a

array([  3.  ,   5.67,   8.33,  11.  ,  13.67,  16.33,  19.  ])