[comment]: # (Created on Mon May 13 20:05:00 2017 @author: Francisco Bustamante @email: chicolucio@gmail.com)
[comment]: # (Exercício nº 2 - capítulo 4 - Python for Science)

# Numpy arrays

In [1]:
import numpy as np

a = np.array([1, 3, 5, 7])
b = np.array([8, 7, 5, 4])
c = np.array([0, 9,-6,-8])

d = list(zip(a, b, c))
print(d, "---", type(d))
print("\n", d[3][2])

e = np.array(d)
print("\n", e, "---", type(e))
print("\n", e[3][2])
print(e[3,2])


[(1, 8, 0), (3, 7, 9), (5, 5, -6), (7, 4, -8)] --- <class 'list'>

 -8

 [[ 1  8  0]
 [ 3  7  9]
 [ 5  5 -6]
 [ 7  4 -8]] --- <class 'numpy.ndarray'>

 -8
-8
