# Chapter 3

***Ver como criar uma tabela de conteúdo TOC**

## Strings

In [1]:
a = "My dog's name is"
b = "Bingo"

In [2]:
c = a + " " + b

In [3]:
c

"My dog's name is Bingo"

In [4]:
#trying to add string and integer
d = "927"
e = 927

In [5]:
d + e

TypeError: must be str, not int

## Lists

In [6]:
a = [0, 1, 1, 2, 3, 5, 8, 13]
b = [5., "girl", 2+0j, "horse", 21]

In [7]:
b[0]

5.0

In [8]:
b[1]

'girl'

<div class="alert alert-block alert-warning">
<big><center>Lists are <span style="color:red"> *zero-indexed*</span> </center></big>
</div>

<div class="alert alert-block alert-success">
$$
\begin{align}
list = &[a, b, c, d, e]\\
&\color{red}\Downarrow
\hspace{2.2pc}\color{red}\Downarrow\\
&\color{purple}{list[0]}
\hspace{1.2pc}
\color{purple}{list[4]}\\
&\color{brown}{list[-5]}
\hspace{0.7pc}
\color{brown}{list[-1]}
\end{align}
$$
</div>

In [9]:
b[-1]

21

In [10]:
b[-5]

5.0

In [11]:
b[4]

21

In [15]:
b = [5., "girl", 2+0j, "horse", 21]
b[0] = b[0]+2
import numpy as np
b[3] = np.pi

In [16]:
b

[7.0, 'girl', (2+0j), 3.141592653589793, 21]

In [17]:
a

[0, 1, 1, 2, 3, 5, 8, 13]

<div class="alert alert-block alert-warning">
<big><center>Adding lists <span style="color:red"> *concatenates*</span> them, just as the **+** operator concatenates strings. </center></big>
</div>

In [18]:
a+a

[0, 1, 1, 2, 3, 5, 8, 13, 0, 1, 1, 2, 3, 5, 8, 13]

### Slicing lists

<div class="alert alert-block alert-warning">
<big>Reparar que <span style="color:red"> *não*</span> se inclui o último elemento.</big>
</div>

In [20]:
b

[7.0, 'girl', (2+0j), 3.141592653589793, 21]

In [21]:
b[1:4]

['girl', (2+0j), 3.141592653589793]

In [22]:
b[3:5]

[3.141592653589793, 21]

In [23]:
b[2:]

[(2+0j), 3.141592653589793, 21]

In [24]:
b[:3]

[7.0, 'girl', (2+0j)]

In [25]:
b[:]

[7.0, 'girl', (2+0j), 3.141592653589793, 21]

In [26]:
b[1:-1]

['girl', (2+0j), 3.141592653589793]

In [27]:
len(b) #len --> length

5

In [1]:
? range

### Creating and modifying lists

<div class="alert alert-block alert-info">
range(stop) -> range object <br>
range(start, stop[, step]) -> range object
</div>

Útil para criar *PAs (progressões aritméticas)*

In [30]:
range(10) #começa de zero por padrão, armazena apenas início, fim e step. Útil para economizar memória

range(0, 10)

In [31]:
print(range(10))

range(0, 10)


In [32]:
list(range(10)) #para explicitar todos os integrantes

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [33]:
list(range(3,10))

[3, 4, 5, 6, 7, 8, 9]

In [34]:
list(range(0,10,2))

[0, 2, 4, 6, 8]

In [35]:
a = range(1,10,3)

In [36]:
a

range(1, 10, 3)

In [37]:
list(a)

[1, 4, 7]

In [38]:
a += [16, 31, 64, 127]

TypeError: unsupported operand type(s) for +=: 'range' and 'list'

In [39]:
a = a + [16, 31, 64,127]

TypeError: unsupported operand type(s) for +: 'range' and 'list'

In [40]:
a = list(a) + [16, 31, 64,127]

In [41]:
a

[1, 4, 7, 16, 31, 64, 127]

In [42]:
a = [0, 0] + a

In [43]:
a

[0, 0, 1, 4, 7, 16, 31, 64, 127]

In [44]:
b = a[:5] + [101, 102] + a[5:]

In [45]:
b

[0, 0, 1, 4, 7, 101, 102, 16, 31, 64, 127]

### Tuples

<div class="alert alert-block alert-warning">
<big><center>**Tuples** are lists that are <span style="color:red"> *immutable*</span></center></big>
</div>

Logo, pode ser usado para armazenar constantes, por exemplo.

In [46]:
c = (1, 1, 2, 3, 5, 8, 13)

In [47]:
c[4]

5

In [48]:
c[4] = 7

TypeError: 'tuple' object does not support item assignment

### Multidimensional lists and tuples

Useful in making tables and other structures.

In [49]:
a = [[3,9], [8,5], [11,1]] #list

In [50]:
a

[[3, 9], [8, 5], [11, 1]]

In [51]:
a[0]

[3, 9]

In [52]:
a[1][0]

8

In [53]:
a[1][0] = 10

In [54]:
a

[[3, 9], [10, 5], [11, 1]]

In [55]:
a = ([3,9], [8,5], [11,1]) #? Não forma tuple assim... tudo deve ser parêntese. Ver abaixo

In [56]:
a[1][0]

8

In [57]:
a[1][0] = 10

In [58]:
a

([3, 9], [10, 5], [11, 1])

In [61]:
a = ((3,9), (8,5), (11,1)) #tuple

In [62]:
a

((3, 9), (8, 5), (11, 1))

In [63]:
a[1][0]

8

In [64]:
a[1][0] = 10

TypeError: 'tuple' object does not support item assignment

## NumPy arrays

- all the elements are of the same type.

In [65]:
import numpy as np

a = [0, 0, 1, 4, 7, 16, 31, 64,127]

In [66]:
a

[0, 0, 1, 4, 7, 16, 31, 64, 127]

In [68]:
b = np.array(a)    #converts a list to an array

In [69]:
b

array([  0,   0,   1,   4,   7,  16,  31,  64, 127])

- the `array` function promotes all of the numbers to the type of the most general entry in the list.

In [72]:
c = np.array([1, 4., -2,7]) #todos se tornarão float

In [73]:
c

array([ 1.,  4., -2.,  7.])

In [74]:
? np.linspace

<div class="alert alert-block alert-info">
np.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)
</div>
Return evenly spaced numbers over a specified interval.

Returns `num` evenly spaced samples, calculated over the interval [`start`, `stop`].

The endpoint of the interval can optionally be excluded.

In [76]:
np.linspace(0, 10, 5)

array([  0. ,   2.5,   5. ,   7.5,  10. ])

In [77]:
np.linspace(0, 10, 5, endpoint=False)

array([ 0.,  2.,  4.,  6.,  8.])

In [78]:
np.linspace(0, 10, 5, retstep=True)

(array([  0. ,   2.5,   5. ,   7.5,  10. ]), 2.5)

In [79]:
? np.logspace

<div class="alert alert-block alert-info">
np.logspace(start, stop, num=50, endpoint=True, base=10.0, dtype=None)
</div>

Return numbers spaced evenly on a log scale.

In linear space, the sequence starts at ``base**start`` (`base` to the power of `start`) and ends with ``base**stop``.

In [80]:
np.logspace(1,3,5)

array([   10.        ,    31.6227766 ,   100.        ,   316.22776602,
        1000.        ])

In [81]:
%precision 1
np.logspace(1,3,5)

array([   10. ,    31.6,   100. ,   316.2,  1000. ])

In [83]:
? np.arange

<div class="alert alert-block alert-info">
arange([start,] stop[, step,], dtype=None)
</div>
Return evenly spaced values within a given interval.

Values are generated within the half-open interval ``[start, stop)`` (in other words, the interval including `start` but excluding `stop`). For integer arguments the function is equivalent to the Python built-in
`range <http://docs.python.org/lib/built-in-funcs.html>`_ function, but returns an ndarray rather than a list.

In [84]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [85]:
np.arange(0., 10, 2)   #todos serão float

array([ 0.,  2.,  4.,  6.,  8.])

In [86]:
np.arange(0, 10, 1.5)

array([ 0. ,  1.5,  3. ,  4.5,  6. ,  7.5,  9. ])

### Criação de arrays de zeros e uns.

In [88]:
np.zeros(6)

array([ 0.,  0.,  0.,  0.,  0.,  0.])

In [89]:
np.ones(8)

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [90]:
np.ones(8, dtype=int)

array([1, 1, 1, 1, 1, 1, 1, 1])

### Mathematical operations with arrays

In [3]:
import numpy as np

a = np.linspace(-1, 5, 7)

In [4]:
a

array([-1.,  0.,  1.,  2.,  3.,  4.,  5.])

In [5]:
a*6

array([ -6.,   0.,   6.,  12.,  18.,  24.,  30.])

In [7]:
np.sin(a)

array([-0.84147098,  0.        ,  0.84147098,  0.90929743,  0.14112001,
       -0.7568025 , -0.95892427])

In [8]:
x = np.linspace(-3.14, 3.14, 21)

In [9]:
y = np.cos(x)

In [10]:
x

array([-3.14 , -2.826, -2.512, -2.198, -1.884, -1.57 , -1.256, -0.942,
       -0.628, -0.314,  0.   ,  0.314,  0.628,  0.942,  1.256,  1.57 ,
        1.884,  2.198,  2.512,  2.826,  3.14 ])

In [12]:
y #fazer o plot disto futuramente

array([ -9.99998732e-01,  -9.50612598e-01,  -8.08267427e-01,
        -5.86882949e-01,  -3.08108031e-01,   7.96326711e-04,
         3.09622813e-01,   5.88171730e-01,   8.09204181e-01,
         9.51105720e-01,   1.00000000e+00,   9.51105720e-01,
         8.09204181e-01,   5.88171730e-01,   3.09622813e-01,
         7.96326711e-04,  -3.08108031e-01,  -5.86882949e-01,
        -8.08267427e-01,  -9.50612598e-01,  -9.99998732e-01])

In [13]:
a

array([-1.,  0.,  1.,  2.,  3.,  4.,  5.])

In [15]:
np.log(a)

/home/chico/anaconda3/lib/python3.6/site-packages/ipykernel/__main__.py:1: RuntimeWarning: divide by zero encountered in log
  if __name__ == '__main__':
/home/chico/anaconda3/lib/python3.6/site-packages/ipykernel/__main__.py:1: RuntimeWarning: invalid value encountered in log
  if __name__ == '__main__':


array([        nan,        -inf,  0.        ,  0.69314718,  1.09861229,
        1.38629436,  1.60943791])

In [16]:
a = np.array([34., -12, 5.])

In [17]:
b = np.array([68., 5., 20.])

In [18]:
a+b #vectorized operations

array([ 102.,   -7.,   25.])

### Slicing and addressing arrays

Fórmula para a velocidade média em um intervalo de tempo *i*:

$$
v_i = \frac{y_i - y_{i-1}}{t_i - t_{i-1}}
$$

In [19]:
y = np.array([0., 1.3, 5., 10.9, 18.9, 28.7, 40.])
t = np.array([0., 0.49, 1., 1.5, 2.08, 2.55, 3.2])

In [20]:
y[:-1]

array([  0. ,   1.3,   5. ,  10.9,  18.9,  28.7])

In [21]:
y[1:]

array([  1.3,   5. ,  10.9,  18.9,  28.7,  40. ])

In [22]:
v = (y[1:]-y[:-1])/(t[1:]-t[:-1])

In [23]:
v

array([  2.65306122,   7.25490196,  11.8       ,  13.79310345,
        20.85106383,  17.38461538])

### Multi-dimensional arrays and matrices

In [24]:
b = np.array([[1., 4, 5], [9, 7, 4]])

In [25]:
b

array([[ 1.,  4.,  5.],
       [ 9.,  7.,  4.]])

In [26]:
#all elements of a MunPy array must be of the same data type: floats, integers, complex numbers, etc.

In [27]:
a = np.ones((3,4), dtype=float)

In [28]:
a

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [29]:
np.eye(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [31]:
c = np.arange(6)

In [32]:
c

array([0, 1, 2, 3, 4, 5])

In [34]:
c = np.reshape(c, (2,3))

In [35]:
c

array([[0, 1, 2],
       [3, 4, 5]])

In [36]:
b

array([[ 1.,  4.,  5.],
       [ 9.,  7.,  4.]])

In [37]:
b[0][2]

5.0

In [40]:
b[0,2] #0 indexed

5.0

In [39]:
b[1,2]

4.0

In [41]:
2*b

array([[  2.,   8.,  10.],
       [ 18.,  14.,   8.]])

<div class="alert alert-block alert-warning">
*Beware*: array multiplication, done on an element-by-element basis, <span, style="color:red">*is not the same as **matrix** multiplication*</span> as defined in linear algebra. Therefore, we distinguish between *array* multiplication and *matrix* multiplication in Python.
</div>

In [42]:
b*c

array([[  0.,   4.,  10.],
       [ 27.,  28.,  20.]])

In [45]:
d = c.T #cria matriz transposta

In [44]:
d

array([[0, 3],
       [1, 4],
       [2, 5]])

In [47]:
np.dot(b,d) #faz multiplicação matricial

array([[ 14.,  44.],
       [ 15.,  75.]])

## Dictionaries

\* Também chamados de *hashmaps* ou *associative arrays* em outras linguagens de programação.

<div class="alert alert-block alert-success">
$$
\begin{align}
room =&\text{{"Emma":309, "Jacob":582, "Olivia":764}}\\
&\hspace{1.0pc}\color{red}\Downarrow
\hspace{1.5pc}\color{red}\Downarrow\\
&\hspace{0.7pc}\color{purple}{key} \hspace{1.5pc}\color{purple}{value}
\end{align}
$$
</div>

In [48]:
room = {"Emma":309, "Jacob":582, "Olivia":764}

In [49]:
room["Olivia"]

764

In [50]:
weird = {"tank":52, 846:"horse", "bones":[23, "fox", "grass"], "phrase":"I am here"}

In [51]:
weird["tank"]

52

In [52]:
weird[846]

'horse'

In [53]:
weird["bones"]

[23, 'fox', 'grass']

In [54]:
weird["phrase"]

'I am here'

In [55]:
d = {}

In [56]:
d["last name"] = "Alberts"
d["first name"] = "Marie"
d["birthday"] = "January 27"

In [57]:
d

{'birthday': 'January 27', 'first name': 'Marie', 'last name': 'Alberts'}

In [58]:
d.keys()

dict_keys(['last name', 'first name', 'birthday'])

In [59]:
d.values()

dict_values(['Alberts', 'Marie', 'January 27'])

## Random numbers

`np.random.rand(num)` creates an array of `num` floats **uniformly** distributed on the interval from 0 to 1.

`np.random.randn(num)` produces a **normal (Gaussian)** distribution of `num` random numbers with a mean of 0 and a standard deviation of 1. They are distributed according to
$$
P(x)=\frac{1}{\sqrt{2\pi}}e^{-\frac{1}{2}x²}
$$

`np.random.randint(low, high, num)` produces a **uniform** random distribution of `num` integers between `low` (inclusive) and `high` (exclusive).

In [61]:
np.random.rand()

0.6128257951854355

In [62]:
np.random.rand(5)

array([ 0.39011104,  0.94966976,  0.82918667,  0.82582458,  0.5470922 ])

In [64]:
a, b = 10, 20
(b-a)*np.random.rand(20) + a #setting interval

array([ 18.77336643,  11.61410374,  14.88429681,  15.51534267,
        13.17639605,  13.1415327 ,  19.31115566,  13.72687979,
        10.54121763,  11.1926624 ,  13.0620921 ,  13.70948059,
        16.47806379,  18.84756575,  17.21223502,  15.50349539,
        12.67808023,  15.71166147,  16.56673275,  19.71620007])

In [65]:
x0, sigma = 15, 10
sigma*np.random.randn(20) + x0 #setting width and center of normal distribution

array([ 16.0341322 ,  24.85431056,  15.82390913,   3.11407242,
         6.59829903,  18.96369418,  18.25224176,   9.49064922,
         1.56663384,   6.72413305,  15.84363561,  21.53336751,
        19.2771351 ,   9.42367517,  -0.57121141,  30.73648204,
        -3.88731961,   8.33712126,   9.68661964,  16.82579145])

In [73]:
np.random.randint(1, 7, 12) #simutaling a dozen rolls of a single die

array([3, 2, 3, 6, 6, 3, 4, 5, 2, 2, 6, 1])