# Exercício 2 do capítulo 3

In [1]:
# letra a

import numpy as np

array_a = np.e * np.ones(100)

In [2]:
array_a

array([ 2.71828183,  2.71828183,  2.71828183,  2.71828183,  2.71828183,
        2.71828183,  2.71828183,  2.71828183,  2.71828183,  2.71828183,
        2.71828183,  2.71828183,  2.71828183,  2.71828183,  2.71828183,
        2.71828183,  2.71828183,  2.71828183,  2.71828183,  2.71828183,
        2.71828183,  2.71828183,  2.71828183,  2.71828183,  2.71828183,
        2.71828183,  2.71828183,  2.71828183,  2.71828183,  2.71828183,
        2.71828183,  2.71828183,  2.71828183,  2.71828183,  2.71828183,
        2.71828183,  2.71828183,  2.71828183,  2.71828183,  2.71828183,
        2.71828183,  2.71828183,  2.71828183,  2.71828183,  2.71828183,
        2.71828183,  2.71828183,  2.71828183,  2.71828183,  2.71828183,
        2.71828183,  2.71828183,  2.71828183,  2.71828183,  2.71828183,
        2.71828183,  2.71828183,  2.71828183,  2.71828183,  2.71828183,
        2.71828183,  2.71828183,  2.71828183,  2.71828183,  2.71828183,
        2.71828183,  2.71828183,  2.71828183,  2.71828183,  2.71

In [3]:
np.e

2.718281828459045

In [4]:
? np.e

In [5]:
array_b = np.linspace(0, 360, 1)

In [6]:
array_b

array([ 0.])

In [1]:
? np.linspace

Object `np.linspace` not found.


In [8]:
array_b = np.linspace(0, 360, 360)

In [9]:
array_b

array([   0.        ,    1.00278552,    2.00557103,    3.00835655,
          4.01114206,    5.01392758,    6.01671309,    7.01949861,
          8.02228412,    9.02506964,   10.02785515,   11.03064067,
         12.03342618,   13.0362117 ,   14.03899721,   15.04178273,
         16.04456825,   17.04735376,   18.05013928,   19.05292479,
         20.05571031,   21.05849582,   22.06128134,   23.06406685,
         24.06685237,   25.06963788,   26.0724234 ,   27.07520891,
         28.07799443,   29.08077994,   30.08356546,   31.08635097,
         32.08913649,   33.09192201,   34.09470752,   35.09749304,
         36.10027855,   37.10306407,   38.10584958,   39.1086351 ,
         40.11142061,   41.11420613,   42.11699164,   43.11977716,
         44.12256267,   45.12534819,   46.1281337 ,   47.13091922,
         48.13370474,   49.13649025,   50.13927577,   51.14206128,
         52.1448468 ,   53.14763231,   54.15041783,   55.15320334,
         56.15598886,   57.15877437,   58.16155989,   59.16434

In [10]:
# melhor usar arange para evitar problema de arredondamento

array_b = np.arange(0, 361, 1) #361 pois é excluído

In [11]:
array_b

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [12]:
array_c = np.radians(array_b)

In [13]:
array_c

array([ 0.        ,  0.01745329,  0.03490659,  0.05235988,  0.06981317,
        0.08726646,  0.10471976,  0.12217305,  0.13962634,  0.15707963,
        0.17453293,  0.19198622,  0.20943951,  0.2268928 ,  0.2443461 ,
        0.26179939,  0.27925268,  0.29670597,  0.31415927,  0.33161256,
        0.34906585,  0.36651914,  0.38397244,  0.40142573,  0.41887902,
        0.43633231,  0.45378561,  0.4712389 ,  0.48869219,  0.50614548,
        0.52359878,  0.54105207,  0.55850536,  0.57595865,  0.59341195,
        0.61086524,  0.62831853,  0.64577182,  0.66322512,  0.68067841,
        0.6981317 ,  0.71558499,  0.73303829,  0.75049158,  0.76794487,
        0.78539816,  0.80285146,  0.82030475,  0.83775804,  0.85521133,
        0.87266463,  0.89011792,  0.90757121,  0.9250245 ,  0.9424778 ,
        0.95993109,  0.97738438,  0.99483767,  1.01229097,  1.02974426,
        1.04719755,  1.06465084,  1.08210414,  1.09955743,  1.11701072,
        1.13446401,  1.15191731,  1.1693706 ,  1.18682389,  1.20

In [14]:
array_d = np.arange(12,17, 0.2)

In [15]:
array_d

array([ 12. ,  12.2,  12.4,  12.6,  12.8,  13. ,  13.2,  13.4,  13.6,
        13.8,  14. ,  14.2,  14.4,  14.6,  14.8,  15. ,  15.2,  15.4,
        15.6,  15.8,  16. ,  16.2,  16.4,  16.6,  16.8])

In [16]:
array_e = np.arange(12,17.1, 0.2)

In [17]:
array_e

array([ 12. ,  12.2,  12.4,  12.6,  12.8,  13. ,  13.2,  13.4,  13.6,
        13.8,  14. ,  14.2,  14.4,  14.6,  14.8,  15. ,  15.2,  15.4,
        15.6,  15.8,  16. ,  16.2,  16.4,  16.6,  16.8,  17. ])