# Exercício 1 do capítulo 3

Evenly spaced --> np.linspace

In [3]:
import numpy as np

r = np.linspace(0,29,9)

In [4]:
r

array([  0.   ,   3.625,   7.25 ,  10.875,  14.5  ,  18.125,  21.75 ,
        25.375,  29.   ])

In [5]:
square_r = r**2

In [6]:
square_r

array([   0.      ,   13.140625,   52.5625  ,  118.265625,  210.25    ,
        328.515625,  473.0625  ,  643.890625,  841.      ])

In [7]:
twice_r = r+r

In [8]:
twice_r

array([  0.  ,   7.25,  14.5 ,  21.75,  29.  ,  36.25,  43.5 ,  50.75,  58.  ])

In [9]:
twice_r_mult = 2*r

In [10]:
twice_r_mult

array([  0.  ,   7.25,  14.5 ,  21.75,  29.  ,  36.25,  43.5 ,  50.75,  58.  ])